 CREATE TABLE XXBCM_ORDER_MGT_STG 
(	
	ORDER_REF 			VARCHAR2(2000), 
	ORDER_DATE 			VARCHAR2(2000), 
	SUPPLIER_NAME 		VARCHAR2(2000), 
	SUPP_CONTACT_NAME 	VARCHAR2(2000), 
	SUPP_ADDRESS 		VARCHAR2(2000), 
	SUPP_CONTACT_NUMBER VARCHAR2(2000), 
	SUPP_EMAIL 			VARCHAR2(2000), 
	ORDER_TOTAL_AMOUNT 	VARCHAR2(2000), 
	ORDER_DESCRIPTION 	VARCHAR2(2000), 
	ORDER_STATUS 		VARCHAR2(2000), 
	ORDER_LINE_AMOUNT 	VARCHAR2(2000), 
	INVOICE_REFERENCE 	VARCHAR2(2000), 
	INVOICE_DATE 		VARCHAR2(2000), 
	INVOICE_STATUS 		VARCHAR2(2000), 
	INVOICE_HOLD_REASON VARCHAR2(2000), 
	INVOICE_AMOUNT 		VARCHAR2(2000), 
	INVOICE_DESCRIPTION VARCHAR2(2000)
) ;

CREATE TABLE XXBCM_SUPPLIERS_TBL
(
    SUPP_NAME VARCHAR2(200),
    CONTACT_FNAME VARCHAR2(100) NOT NULL,
    CONTACT_LNAME VARCHAR2(100) NOT NULL,
    STREET VARCHAR2(200),
    CITY VARCHAR2(100),
    COUNTRY VARCHAR2(100),
    TEL_NUM VARCHAR2(7),
    MOB_NUM VARCHAR2(8),
    EMAIL VARCHAR2(100),
    CONSTRAINT XXBCM_SUPP_PK PRIMARY KEY (SUPP_NAME)
);


CREATE TABLE XXBCM_TRANSACTIONS_TBL
(
    ORDER_REF VARCHAR2(10),
    ORDER_DATE DATE NOT NULL,
    TOTAL_AMT NUMERIC(18,2),
    ORDER_DESCRIPTION VARCHAR2(300),
    ORDER_STATUS VARCHAR2(15),
    LINE_AMT NUMERIC(18,2),
	INV_REF VARCHAR2(15),
	INV_DATE DATE NOT NULL,
	INV_STATUS VARCHAR2(15),
	INV_HOLD_REASON VARCHAR2(200),
	INV_AMOUNT NUMERIC(18,2),
	INV_DESCRIPTION VARCHAR2(200),
    SUPP_NAME VARCHAR2(200),
    FOREIGN KEY (SUPP_NAME)
    REFERENCES XXBCM_SUPPLIERS_TBL (SUPP_NAME),
    CONSTRAINT XXBCM_ODR_STATUS_CHK
    CHECK (ORDER_STATUS IN('Cancelled', 'Closed', 'Received', 'Open')),
	CONSTRAINT XXBCM_INV_STATUS_CHK
CHECK (INV_STATUS IN('Paid', 'Pending', ''))
);
  